global using Microsoft.EntityFrameworkCore;
global using System.Collections.Generic;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;

//global using BrotaAPI.Domain.Exceptions;
global using BrotaAPI.Domain.Repositories;
//global using BrotaAPI.Domain.HttpHelpers;
global using BrotaAPI.Domain.Config;
global using BrotaAPI.Domain.Services;
global using BrotaAPI.Domain.Models;
//global using BrotaAPI.Domain.Dtos;
//global using BrotaAPI.Domain.Enums;
global using BrotaAPI.Repositories;
//global using BrotaAPI.Config;
global using BrotaAPI.Services;
//global using BrotaAPI.Middlewares;
global using BrotaAPI.Config;